/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package tp4.Dessin;

import java.awt.Graphics;
import java.awt.Point;

/**
 *
 * @author alphaoumar
 */
public class Dessin extends javax.swing.JPanel {

    private FormDrawable figure;
    /**
     * Creates new form Dessin
     */
    public Dessin() {
        initComponents();
        figure = null;
    }

    @Override
    public void paint(Graphics grphcs) {
        super.paint(grphcs); //To change body of generated methods, choose Tools | Templates.
        if(getType() != null){
            figure.draw(grphcs);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 398, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 298, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables


    /**
     * @return the p2
     */
    public Point getP2() {
        return figure.getP2();
    }

    /**
     * @param p2 the p2 to set
     */
    public void setP2(Point p2) {
        figure.setP2(p2);
    }

    /**
     * @return the figure
     */
    public FormDrawable getType() {
        return figure;
    }

    /**
     * @param figure the figure to set
     */
    public void setType(FormDrawable type) {
        this.figure = type;
    }
}
