/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package tp3;

/**
 *
 * @author 21007631
 */
public class Feu extends javax.swing.JPanel {

    /**
     * Creates new form Feu
     */
    public Feu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        redAmpoule = new tp3.Ampoule();
        orangeAmpoule = new tp3.Ampoule();
        greenAmpoule = new tp3.Ampoule();

        redAmpoule.setCouleurFeu(new java.awt.Color(204, 0, 51));

        javax.swing.GroupLayout redAmpouleLayout = new javax.swing.GroupLayout(redAmpoule);
        redAmpoule.setLayout(redAmpouleLayout);
        redAmpouleLayout.setHorizontalGroup(
            redAmpouleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        redAmpouleLayout.setVerticalGroup(
            redAmpouleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        orangeAmpoule.setCouleurFeu(new java.awt.Color(255, 204, 0));

        javax.swing.GroupLayout orangeAmpouleLayout = new javax.swing.GroupLayout(orangeAmpoule);
        orangeAmpoule.setLayout(orangeAmpouleLayout);
        orangeAmpouleLayout.setHorizontalGroup(
            orangeAmpouleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        orangeAmpouleLayout.setVerticalGroup(
            orangeAmpouleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        greenAmpoule.setCouleurFeu(new java.awt.Color(102, 255, 0));

        javax.swing.GroupLayout greenAmpouleLayout = new javax.swing.GroupLayout(greenAmpoule);
        greenAmpoule.setLayout(greenAmpouleLayout);
        greenAmpouleLayout.setHorizontalGroup(
            greenAmpouleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        greenAmpouleLayout.setVerticalGroup(
            greenAmpouleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(redAmpoule, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(orangeAmpoule, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(greenAmpoule, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(greenAmpoule, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(orangeAmpoule, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(redAmpoule, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private tp3.Ampoule greenAmpoule;
    private tp3.Ampoule orangeAmpoule;
    private tp3.Ampoule redAmpoule;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the greenAmpoule
     */
    public tp3.Ampoule getGreenAmpoule() {
        return greenAmpoule;
    }

    /**
     * @return the orangeAmpoule
     */
    public tp3.Ampoule getOrangeAmpoule() {
        return orangeAmpoule;
    }

    /**
     * @return the redAmpoule
     */
    public tp3.Ampoule getRedAmpoule() {
        return redAmpoule;
    }
}
