/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package tp4.Form;

import javax.swing.DefaultListModel;

/**
 *
 * @author 21007631
 */
public class Form extends javax.swing.JFrame {
    private enum State{E_INIT, E_AFFICHER, E_MODIFIER};
    private DefaultListModel<Enregistrement> liste;
    private State currentState;
    private Enregistrement currentEnr, tmpEnr;
    
    public void addElement(){
        if(isCorrect()){
            currentEnr = new Enregistrement(vTitre.getText(), 1);
            liste.addElement(currentEnr);
        }
        
    }
    public void removeElement(){
        liste.removeElement(currentEnr);
    }
    public void remplacerElement(Enregistrement e){
        if(isCorrect()){
            tmpEnr = currentEnr;
            for(int i=0; i < liste.size(); i++)
            if(liste.get(i).getName().equals(currentEnr.getName())){
                liste.set(i, e);
                currentEnr = e;
                break;
            } 
        }  
    }
    public void retablirElement(){
        if(tmpEnr != null){
            for(int i=0; i < liste.size(); i++)
                if(liste.get(i).getName().equals(currentEnr.getName())){
                        liste.set(i, tmpEnr);
                        currentEnr = tmpEnr;
                        break;
                 }
        }
        
    }
    public boolean isCorrect(){
        if(vTitre.getText().isEmpty() && (!val1.isSelected()
                || !val2.isSelected() || !val3.isSelected()))
            return false;
        return true;
    }
    public void activation(){
        switch(currentState){
            case E_INIT:
                bAjouter.setEnabled(true);
                bSupprimer.setEnabled(false);
                bRemplacer.setEnabled(false);
                bRetablir.setEnabled(false);
                break;
            case E_AFFICHER:
                bAjouter.setEnabled(false);
                bSupprimer.setEnabled(true);
                bRemplacer.setEnabled(true);
                bRetablir.setEnabled(true);
                break;
            case E_MODIFIER:
                bAjouter.setEnabled(false);
                bSupprimer.setEnabled(false);
                bRemplacer.setEnabled(true);
                bRetablir.setEnabled(true);
                break;
        }
    }
    /**
     * Creates new form Form
     */
    public Form() {
        this.liste = new DefaultListModel<>();
        currentState = State.E_INIT;
        initComponents();
        this.jList.setModel(liste);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        lTitre = new javax.swing.JLabel();
        vTitre = new javax.swing.JTextField();
        val1 = new javax.swing.JRadioButton();
        val2 = new javax.swing.JRadioButton();
        val3 = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList = new javax.swing.JList();
        bAjouter = new javax.swing.JButton();
        bRetablir = new javax.swing.JButton();
        bSupprimer = new javax.swing.JButton();
        bRemplacer = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lTitre.setText("Titre");

        vTitre.setText("jTextField1");
        vTitre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vTitreActionPerformed(evt);
            }
        });
        vTitre.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                vTitrePropertyChange(evt);
            }
        });

        buttonGroup1.add(val1);
        val1.setText("1");

        buttonGroup1.add(val2);
        val2.setText("2");

        buttonGroup1.add(val3);
        val3.setText("3");

        jList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jListValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jList);

        bAjouter.setText("Ajouter");
        bAjouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAjouterActionPerformed(evt);
            }
        });

        bRetablir.setText("Retablir");
        bRetablir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bRetablirActionPerformed(evt);
            }
        });

        bSupprimer.setText("Supprimer");
        bSupprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSupprimerActionPerformed(evt);
            }
        });

        bRemplacer.setText("Remplacer");
        bRemplacer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bRemplacerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lTitre)
                        .addGap(18, 18, 18)
                        .addComponent(vTitre, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(val1)
                        .addGap(18, 18, 18)
                        .addComponent(val2)
                        .addGap(18, 18, 18)
                        .addComponent(val3)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bAjouter)
                    .addComponent(bRetablir)
                    .addComponent(bSupprimer)
                    .addComponent(bRemplacer))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lTitre)
                    .addComponent(vTitre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(val1)
                    .addComponent(val2)
                    .addComponent(val3))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(bAjouter)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bRetablir)
                        .addGap(18, 18, 18)
                        .addComponent(bSupprimer)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bRemplacer)
                        .addContainerGap(54, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bAjouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAjouterActionPerformed
        // TODO add your handling code here:
        switch(currentState){
            case E_INIT:
                currentState = State.E_AFFICHER;
                activation();
                addElement();
                break;
            case E_AFFICHER:
                throw new RuntimeException("E_AFFICHER INTERDIT");
            case E_MODIFIER:
                currentState = State.E_AFFICHER;
                activation();
                addElement();
                break;
        }
        
        
    }//GEN-LAST:event_bAjouterActionPerformed

    private void bRetablirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bRetablirActionPerformed
        // TODO add your handling code here:
        switch(currentState){
            case E_INIT:
                throw new RuntimeException("E_INIT INTERDIT");
            case E_AFFICHER:
                throw new RuntimeException("E_AFFICHER INTERDIT");
            case E_MODIFIER:
                currentState = State.E_AFFICHER;
                this.retablirElement();
                activation();
                break;
        }
    }//GEN-LAST:event_bRetablirActionPerformed

    private void bSupprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSupprimerActionPerformed
        // TODO add your handling code here:
        switch(currentState){
            case E_INIT:
                throw new RuntimeException("E_INIT INTERDIT");
            case E_AFFICHER:
                if(liste.size() > 1){
                    currentState = State.E_AFFICHER;
                    removeElement();
                    activation();
                }else if(liste.size() == 1){
                    currentState = State.E_INIT;
                    removeElement();
                    activation();
                }
                break;
            case E_MODIFIER:
                throw new RuntimeException("E_MODIFIER INTERDIT");
        }
    }//GEN-LAST:event_bSupprimerActionPerformed

    private void bRemplacerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bRemplacerActionPerformed
        // TODO add your handling code here:
        switch(currentState){
            case E_INIT:
                throw new RuntimeException("E_INIT INTERDIT");
            case E_AFFICHER:
                throw new RuntimeException("E_AFFICHER INTERDIT");
            case E_MODIFIER:
                currentState = State.E_AFFICHER;
                remplacerElement(currentEnr);
                activation();
                break;
        }
    }//GEN-LAST:event_bRemplacerActionPerformed

    private void jListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jListValueChanged
        // TODO add your handling code here:
        switch(currentState){
            case E_INIT:
                throw new RuntimeException("E_INIT INTERDIT");
            case E_AFFICHER:
                currentState = State.E_AFFICHER;
                currentEnr = liste.get(jList.getSelectedIndex());
                activation();
                break;
            case E_MODIFIER:
                currentState = State.E_MODIFIER;
                currentEnr = liste.get(jList.getSelectedIndex());
                activation();
                break;
        }
    }//GEN-LAST:event_jListValueChanged

    private void vTitreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vTitreActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_vTitreActionPerformed

    private void vTitrePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_vTitrePropertyChange
        // TODO add your handling code here:
        System.out.println("vtrite");
    }//GEN-LAST:event_vTitrePropertyChange

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAjouter;
    private javax.swing.JButton bRemplacer;
    private javax.swing.JButton bRetablir;
    private javax.swing.JButton bSupprimer;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JList jList;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lTitre;
    private javax.swing.JTextField vTitre;
    private javax.swing.JRadioButton val1;
    private javax.swing.JRadioButton val2;
    private javax.swing.JRadioButton val3;
    // End of variables declaration//GEN-END:variables
}
