/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package tp3;

import java.awt.Color;
import java.awt.Graphics;

/**
 *
 * @author 21007631
 */
public class Ampoule extends javax.swing.JPanel {

    private boolean allumer = true;
    private Color couleurFeu = Color.BLUE;
    /**
     * Creates new form Ampoule
     */
    public Ampoule() {
        initComponents();
    }

    @Override
    public void paint(Graphics g) {
        super.paint(g); //To change body of generated methods, choose Tools | Templates.
        g.setColor(couleurFeu);
        g.drawOval(0, 0, getWidth(), getHeight());
        if(isAllumer())
            g.fillOval(0, 0, getWidth(), getHeight());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

    /**
     * @return the allumer
     */
    public boolean isAllumer() {
        return allumer;
    }

    /**
     * @param allumer the allumer to set
     */
    public void setAllumer(boolean allumer) {
        this.allumer = allumer;
    }

    /**
     * @return the couleurFeu
     */
    public Color getCouleurFeu() {
        return couleurFeu;
    }

    /**
     * @param couleurFeu the couleurFeu to set
     */
    public void setCouleurFeu(Color couleurFeu) {
        this.couleurFeu = couleurFeu;
    }
}
